credentials:
  usernames:
    usuario1:
      email: geologiayestudios@gmail.com
      name: geologia
      password: $2b$12$lNQRSlA.ce3KkH/wCxuJOezBNG7QhyPf.3G6C75vTDg0nRfqN0oJy
 

cookie:
  name: hydropick_cookie
  key: super_secret_key_random_2026
  expiry_days: 30