credentials:
  usernames:
    usuario1:
      email: geologiayestudios@gmail.com
      name: geologia
      password: Exitoso1
 

cookie:
  name: hydropick_cookie
  key: super_secret_key_random_2026
  expiry_days: 30