credentials:
  usernames:
    usuario1:
      email: geologiayestudios@gmail.com
      name: geologia
      password: $2b$12$8vK9pL3mN5qR7tV9xZ2aB4cD6eF8gH0iJ2kL4mN6oP8qR0tV2wX
 

cookie:
  name: hydropick_cookie
  key: super_secret_key_random_2026
  expiry_days: 30